# Generated by Django 5.2.3 on 2025-11-10 08:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('common_name', models.CharField(blank=True, max_length=100)),
                ('kingdom', models.CharField(choices=[('Plant', 'Plant'), ('Animal', 'Animal'), ('Fungus', 'Fungus'), ('Bacteria', 'Bacteria'), ('Virus', 'Virus'), ('Archaea', 'Archaea')], max_length=50)),
                ('taxonomy_id', models.PositiveIntegerField(blank=True, help_text='NCBI taxonomy ID', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('DNA', 'DNA-seq'), ('RNA', 'RNA-seq'), ('META', 'Metagenomics'), ('PROT', 'Proteomics'), ('METAB', 'Metabolomics')], max_length=10)),
                ('collected_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='omics_core.organism')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='omics_core.project')),
            ],
        ),
        migrations.CreateModel(
            name='OmicsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='results/')),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='omics_core.sample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OmicsJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('FASTQC', 'Quality Control'), ('ALIGN', 'Read Alignment'), ('VARCALL', 'Variant Calling'), ('EXPR', 'Expression Analysis'), ('ANNOT', 'Annotation'), ('CUSTOM', 'Custom Script')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('output_path', models.CharField(blank=True, max_length=255)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='omics_core.sample')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OmicsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('FASTQ', 'FASTQ reads'), ('BAM', 'Aligned reads'), ('VCF', 'Variant calls'), ('GFF', 'Genome annotation'), ('COUNTS', 'Expression counts'), ('META', 'Metadata table'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='omics_core.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SampleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1, help_text='Current wizard step')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Serialized wizard data')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Associated project for this draft entry', on_delete=django.db.models.deletion.CASCADE, related_name='sample_drafts', to='omics_core.project')),
                ('user', models.ForeignKey(blank=True, help_text='User who created this draft', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TissueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kingdom', models.CharField(choices=[('Plant', 'Plant'), ('Animal', 'Animal'), ('Fungus', 'Fungus'), ('Bacteria', 'Bacteria'), ('Virus', 'Virus'), ('Archaea', 'Archaea')], max_length=50)),
                ('ontology_id', models.CharField(blank=True, help_text='UBERON / PO term ID', max_length=50)),
            ],
            options={
                'ordering': ['kingdom', 'name'],
                'unique_together': {('name', 'kingdom')},
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='tissue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='omics_core.tissuetype'),
        ),
    ]
