# Generated by Django 5.2.7 on 2025-11-05 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('organism', models.CharField(max_length=200)),
                ('tissue_type', models.CharField(blank=True, max_length=200)),
                ('data_type', models.CharField(choices=[('DNA', 'DNA-seq'), ('RNA', 'RNA-seq'), ('META', 'Metagenomics'), ('PROT', 'Proteomics'), ('METAB', 'Metabolomics')], max_length=10)),
                ('collected_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='omics_core.project')),
            ],
        ),
        migrations.CreateModel(
            name='OmicsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('FASTQ', 'FASTQ reads'), ('BAM', 'Aligned reads'), ('VCF', 'Variant calls'), ('GFF', 'Genome annotation'), ('COUNTS', 'Expression counts'), ('META', 'Metadata table'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='omics_core.sample')),
            ],
        ),
    ]
