# Generated by Django 5.2.7 on 2025-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='omicsjob',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
