# Generated by Django 5.2.7 on 2025-11-15 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omics_core', '0002_omicsjob_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='search_name',
            field=models.CharField(db_index=True, default='', help_text='Lowercased scientific_name for fast indexed search', max_length=200),
        ),
        migrations.AlterField(
            model_name='organism',
            name='kingdom',
            field=models.CharField(choices=[('Plant', 'Plant'), ('Animal', 'Animal'), ('Fungus', 'Fungus'), ('Bacteria', 'Bacteria'), ('Virus', 'Virus'), ('Archaea', 'Archaea'), ('Eukaryota', 'Eukaryota')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sampledraft',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sampledraft',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_drafts', to='omics_core.project'),
        ),
        migrations.AlterField(
            model_name='sampledraft',
            name='step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sampledraft',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sample_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tissuetype',
            name='kingdom',
            field=models.CharField(choices=[('Plant', 'Plant'), ('Animal', 'Animal'), ('Fungus', 'Fungus'), ('Bacteria', 'Bacteria'), ('Virus', 'Virus'), ('Archaea', 'Archaea'), ('Eukaryota', 'Eukaryota')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tissuetype',
            name='ontology_id',
            field=models.CharField(blank=True, help_text='UBERON or PO term ID', max_length=50),
        ),
    ]
